namespace AuthManager.Core.Services;

/// <summary>
/// Sends a text message through whichever SMS provider is active in
/// <see cref="Options.SmsOptions"/> (Twilio, Vonage, MessageBird, Sinch, or Textlocal).
/// Provider credentials are managed through <see cref="ISmsSettingsService"/>.
///
/// Typical use — deliver an OTP code generated by <see cref="IOtpService"/>:
/// <code>
/// var otp = await otpService.GenerateAsync(user.Id, "login");
/// var message = otpOptions.SmsBodyTemplate
///     .Replace("{code}", otp.PlainCode)
///     .Replace("{appName}", options.Title)
///     .Replace("{expiry}", "10 minutes");
/// await smsSender.SendAsync(user.PhoneNumber, message);
/// </code>
/// </summary>
public interface ISmsSenderService
{
    /// <summary>
    /// Sends <paramref name="message"/> to <paramref name="toPhoneNumber"/> (E.164 format,
    /// e.g. <c>+447911123456</c>) via the currently active SMS provider.
    /// </summary>
    Task<(bool Success, string[] Errors)> SendAsync(
        string toPhoneNumber, string message, CancellationToken ct = default);
}
