using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace AuthManager.SourceGenerator;

/// <summary>
/// Roslyn incremental source generator that detects whether the consuming project has
/// ASP.NET Identity set up. If not, it emits scaffolded Identity boilerplate (ApplicationUser,
/// ApplicationDbContext, and Program.cs wiring suggestions) based on MSBuild properties
/// set by the developer in their .csproj.
///
/// Usage — add to .csproj:
///   &lt;PropertyGroup&gt;
///     &lt;AuthManagerScaffoldIdentity&gt;true&lt;/AuthManagerScaffoldIdentity&gt;
///     &lt;AuthManagerRootNamespace&gt;MyApp&lt;/AuthManagerRootNamespace&gt;
///     &lt;AuthManagerDbContextName&gt;ApplicationDbContext&lt;/AuthManagerDbContextName&gt;
///     &lt;AuthManagerUserName&gt;ApplicationUser&lt;/AuthManagerUserName&gt;
///     &lt;AuthManagerSeparateLibrary&gt;false&lt;/AuthManagerSeparateLibrary&gt;
///     &lt;AuthManagerDbProvider&gt;SqlServer&lt;/AuthManagerDbProvider&gt;
///   &lt;/PropertyGroup&gt;
/// </summary>
[Generator]
public sealed class IdentityScaffoldGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Read MSBuild properties
        var scaffoldProp = context.AnalyzerConfigOptionsProvider
            .Select((opts, _) =>
            {
                opts.GlobalOptions.TryGetValue("build_property.AuthManagerScaffoldIdentity", out var scaffold);
                opts.GlobalOptions.TryGetValue("build_property.AuthManagerRootNamespace", out var ns);
                opts.GlobalOptions.TryGetValue("build_property.AuthManagerDbContextName", out var ctx);
                opts.GlobalOptions.TryGetValue("build_property.AuthManagerUserName", out var user);
                opts.GlobalOptions.TryGetValue("build_property.AuthManagerDbProvider", out var provider);
                opts.GlobalOptions.TryGetValue("build_property.AuthManagerSeparateLibrary", out var sep);
                opts.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNs);

                return new ScaffoldConfig(
                    Enabled: scaffold?.Trim().ToLowerInvariant() == "true",
                    Namespace: ns ?? rootNs ?? "MyApp",
                    DbContextName: ctx ?? "ApplicationDbContext",
                    UserName: user ?? "ApplicationUser",
                    DbProvider: provider ?? "SqlServer",
                    SeparateLibrary: sep?.Trim().ToLowerInvariant() == "true"
                );
            });

        context.RegisterSourceOutput(scaffoldProp, (spc, config) =>
        {
            if (!config.Enabled) return;

            spc.AddSource("ApplicationUser.g.cs",        GenerateApplicationUser(config));
            spc.AddSource("ApplicationDbContext.g.cs",   GenerateDbContext(config));
            spc.AddSource("AuthManagerSetupHints.g.cs",  GenerateSetupHints(config));
        });
    }

    private static string GenerateApplicationUser(ScaffoldConfig cfg) => $$"""
        // <auto-generated by DotNetAuthManager.SourceGenerator />
        // This file was scaffolded because <AuthManagerScaffoldIdentity>true</AuthManagerScaffoldIdentity>
        // Remove this property from your .csproj once you have customised this class.
        using Microsoft.AspNetCore.Identity;

        namespace {{cfg.Namespace}}.Identity;

        /// <summary>
        /// Application user extending ASP.NET Identity's IdentityUser.
        /// Add your custom profile properties here.
        /// </summary>
        public class {{cfg.UserName}} : IdentityUser
        {
            /// <summary>User's full display name.</summary>
            public string? FullName { get; set; }

            /// <summary>UTC timestamp of the user's last login.</summary>
            public DateTimeOffset? LastLoginAt { get; set; }

            /// <summary>Custom profile picture URL.</summary>
            public string? AvatarUrl { get; set; }
        }
        """;

    private static string GenerateDbContext(ScaffoldConfig cfg)
    {
        var userNs = $"{cfg.Namespace}.Identity";
        var storeNs = cfg.DbProvider switch
        {
            "PostgreSQL" => "Npgsql.EntityFrameworkCore.PostgreSQL",
            "MySql"      => "Pomelo.EntityFrameworkCore.MySql",
            _            => "Microsoft.EntityFrameworkCore.SqlServer"
        };

        return $$"""
            // <auto-generated by DotNetAuthManager.SourceGenerator />
            using {{userNs}};
            using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
            using Microsoft.EntityFrameworkCore;

            namespace {{cfg.Namespace}}.Data;

            /// <summary>
            /// Application database context with ASP.NET Identity support.
            /// </summary>
            public class {{cfg.DbContextName}} : IdentityDbContext<{{cfg.UserName}}>
            {
                public {{cfg.DbContextName}}(DbContextOptions<{{cfg.DbContextName}}> options)
                    : base(options) { }

                protected override void OnModelCreating(ModelBuilder builder)
                {
                    base.OnModelCreating(builder);
                    // Customize Identity table names if desired:
                    // builder.Entity<{{cfg.UserName}}>().ToTable("Users");
                }
            }
            """;
    }

    private static string GenerateSetupHints(ScaffoldConfig cfg)
    {
        var pkg = cfg.DbProvider switch
        {
            "PostgreSQL" => "DotNetAuthManager.Storage.PostgreSQL",
            "MySql"      => "DotNetAuthManager.Storage.MySql",
            _            => "DotNetAuthManager.Storage.SqlServer"
        };

        var method = cfg.DbProvider switch
        {
            "PostgreSQL" => "AddAuthManagerWithPostgreSQL",
            "MySql"      => "AddAuthManagerWithMySql",
            _            => "AddAuthManagerWithSqlServer"
        };

        return $$"""
            // <auto-generated by DotNetAuthManager.SourceGenerator />
            // ========================================================
            // DotNetAuthManager — Program.cs wiring hints
            // Reference package: {{pkg}}
            // ========================================================
            //
            // Add to your Program.cs:
            //
            //   using {{cfg.Namespace}}.Identity;
            //
            //   builder.Services.{{method}}<{{cfg.UserName}}>(
            //       connectionString: builder.Configuration.GetConnectionString("Default")!,
            //       authManager: options =>
            //       {
            //           options.RoutePrefix = "authmanager";
            //           options.DefaultTheme = AuthManager.Core.Options.AuthManagerTheme.Dark;
            //           options.AdminRoles = ["Admin"];
            //       }
            //   );
            //
            //   var app = builder.Build();
            //   app.UseAuthentication();
            //   app.UseAuthorization();
            //   app.MapAuthManager();
            //

            namespace {{cfg.Namespace}};

            /// <summary>DotNetAuthManager scaffolding hints — safe to delete once set up.</summary>
            internal static class AuthManagerSetupHints { }
            """;
    }

    private sealed record ScaffoldConfig(
        bool Enabled,
        string Namespace,
        string DbContextName,
        string UserName,
        string DbProvider,
        bool SeparateLibrary);
}
